version: '2'
services:
  rezzy_1:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    links:
      - rezzy-db
    environment:
      MYSQL_HOST: rezzy-db
      MYSQL_ROOT_PASSWORD: __Goalie31__
      MYSQL_USER: web_app
      MYSQL_PASSWORD: __Goalie31__
      MYSQL_DATABASE: wedding_jonfreer_com
      MYSQL_PORT: 3306

  rezzy_2:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    links:
      - rezzy-db
    environment:
      MYSQL_HOST: rezzy-db
      MYSQL_ROOT_PASSWORD: __Goalie31__
      MYSQL_USER: web_app
      MYSQL_PASSWORD: __Goalie31__
      MYSQL_DATABASE: wedding_jonfreer_com
      MYSQL_PORT: 3306

  rezzy-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: __Goalie31__
      MYSQL_USER: web_app
      MYSQL_PASSWORD: __Goalie31__
      MYSQL_DATABASE: wedding_jonfreer_com
    volumes:
      - ./mysql/:/etc/mysql/conf.d
      - ./mysql_startup_scripts/:/docker-entrypoint-initdb.d

  rezzy-proxy:
    image: nginx:latest
    ports:
      - "9090:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - rezzy_1
      - rezzy_2

